spring.application.name=microsservice-reserva


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/reserva_db
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root1234}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

services.usuario.url=${URL_USER:http://localhost:8081}
services.sala.url=${URL_SALA:http://localhost:8082}


server.port=${SERVER_PORT:8083}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}
